theme = "hugo-now-ui"
baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Now UI Kit"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

##[[menu.main]]
##    name = "Firm"
##    url = "/components"
##    weight = 1
##[[menu.main]]
##    name = "Our Team"
##    url = "/landing"
##    weight = 1
##[[menu.main]]
##    name = "Our Expertise"
##    url = "/profile"
##    weight = 2  #/
[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3
    
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/meifg"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/meifg"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    background = "/img/bg11.jpg"
    tint = "orange"
    custom_css = ["css/highlight.min.css", "css/base.css", "css/homepage.css" ]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "MEI Financial Group"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


    

