theme = "hugo-now-ui"
baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "MEI Financial Group"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Our Firm"
    url = "/firm"
    weight = 1
[[menu.main]]
    name = "Our Team"
    url = "/team"
    weight = 2
[[menu.main]]
    name = "Our Expertise"
    url = "/expertise"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[[menu.footer]]
    identifier = "Legal Notice"
    name = "Legal Notice"
    url = "/legalnotice"
    weight = 1
[[menu.footer]]
    identifier = "Privacy Policy"
    name = "Privacy Policy"
    url = "/privacypolicy"
    weight = 2


[params]
    background = "/img/bg11.jpg"
    tint = "orange"
    custom_css = ["css/highlight.min.css", "css/base.css", "css/homepage.css" ]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "MEI Financial Group"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
